name: Genera Space Invaders

on:
  schedule:
    - cron: "0 0 * * *"   # ogni giorno alle 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Genera space-invaders-contribution-graph1.svg
        env:
          GITHUB_USER_NAME: ${{ github.repository_owner }}
          # Opzionale se vuoi interrogare la GraphQL API per le contribution:
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/generate-space-invaders.mjs

      - name: Pubblica su branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
